# Generated by Django 3.0 on 2024-03-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='NewAddress',
        ),
        migrations.RenameModel(
            old_name='Letting',
            new_name='NewLetting',
        ),
    ]
