# Generated by Django 3.0 on 2024-03-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0003_auto_20240326_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewAddress',
            new_name='Address',
        ),
        migrations.RenameModel(
            old_name='NewLetting',
            new_name='Letting',
        ),
    ]
