# Generated by Django 3.0 on 2024-03-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0004_auto_20240327_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
