name: GitHub Actions Demo
run-name: Pipeline is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install python3-pip;
      - run: pip install -r requirements.txt
      - run: pytest