name: GitHub Actions Integration

on:
  push:
    branches:
      - '**'

jobs:
  compilations_and_tests:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python and dependencies
        run: |
          sudo apt update
          sudo apt install python3-pip
          pip3 install -r requirements.txt
          pip3 install pytest pytest-cov

      - name: Run Tests whit Coverage
        run: pytest

      - name: Run Linting
        run: flake8

  containerization_and_push:
    runs-on: ubuntu-latest

    needs: compilations_and_tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Docker image to ECR and DockerHub
        run: |
          cd $(git rev-parse --show-toplevel) && COMMIT_HASH=$(git rev-parse --short HEAD)
          docker build -t python-oc-lettings-fr:$COMMIT_HASH -f Dockerfile .

      - name: Push Docker image to ECR
        run: |
          cd $(git rev-parse --show-toplevel) && COMMIT_HASH=$(git rev-parse --short HEAD)
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_URL_REPOSITORY
          docker tag python-oc-lettings-fr:$COMMIT_HASH $ECR_URL_REPOSITORY:$COMMIT_HASH
          docker push $ECR_URL_REPOSITORY:$COMMIT_HASH
        env:
          ECR_URL_REPOSITORY: ${{ secrets.ECR_URL_REPOSITORY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Push Docker image to DockerHub and to local
        run: |
          cd $(git rev-parse --show-toplevel) && COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker tag python-oc-lettings-fr:$COMMIT_HASH $DOCKERHUB_USERNAME/python-oc-lettings-fr:$COMMIT_HASH
          docker push $DOCKERHUB_USERNAME/python-oc-lettings-fr:$COMMIT_HASH
          docker pull $DOCKERHUB_USERNAME/python-oc-lettings-fr:$COMMIT_HASH
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}


  build:
    runs-on: ubuntu-latest

    needs: containerization_and_push

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Update ECS Task Definition
        run: |
          cd $(git rev-parse --show-toplevel) && COMMIT_HASH=$(git rev-parse --short HEAD)
          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition lettings-oc-docker --region $AWS_REGION)
          NEW_TASK_DEFINITION=$(echo "$TASK_DEFINITION" | jq --arg IMAGE $ECR_URL_REPOSITORY:$COMMIT_HASH '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) |  del(.registeredAt) | del(.registeredBy)')
          NEW_TASK_INFO=$(aws ecs register-task-definition --region $AWS_REGION --cli-input-json "$NEW_TASK_DEFINITION")
          NEW_REVISION=$(echo $NEW_TASK_INFO | jq '.taskDefinition.revision')
          aws ecs update-service --cluster lettings-fr --service python-oc-lettings-fr --task-definition lettings-oc-docker:$NEW_REVISION --force-new-deployment --region $AWS_REGION
        env:
          ECR_URL_REPOSITORY: ${{ secrets.ECR_URL_REPOSITORY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
