name: GitHub Actions Integration

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python and dependencies
        run: |
          sudo apt update
          sudo apt install python3-pip
          pip3 install -r requirements.txt

      - name: Run Pytest
        run: pytest
